version: "3.9"

services:

  db:
    image: mysql:8
    container_name: lms_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "Pavan@9589"
      MYSQL_DATABASE: "LMS"
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: lms_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=mysql+pymysql://root:Pavan@9589@db:3306/LMS
    depends_on:
      - db
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build: ./frontend/lms_frontend
    container_name: lms_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/lms_frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    stdin_open: true

volumes:
  mysql_data: